from enum import Enum


class CallState(str, Enum):
    INITIALIZING = "INITIALIZING"
    DNC_CHECK = "DNC_CHECK"
    DISCLOSURE = "DISCLOSURE"
    CONSENT = "CONSENT"
    WELCOME = "WELCOME"
    RECOVER_CONTEXT = "RECOVER_CONTEXT"
    COLLECTING = "COLLECTING"
    CONFIRMING = "CONFIRMING"
    CLARIFYING = "CLARIFYING"
    SUBMITTING = "SUBMITTING"
    COMPLETED = "COMPLETED"
    ESCALATING = "ESCALATING"
    HANDOFF = "HANDOFF"
    DECLINED = "DECLINED"
    ENDED = "ENDED"


class CustomerEvent(str, Enum):
    CUSTOMER_INTERRUPT = "CUSTOMER_INTERRUPT"
    CUSTOMER_BUSY = "CUSTOMER_BUSY"
    CUSTOMER_NOT_INTERESTED = "CUSTOMER_NOT_INTERESTED"
    CUSTOMER_QUESTION = "CUSTOMER_QUESTION"
    CUSTOMER_CORRECTION = "CUSTOMER_CORRECTION"
    CUSTOMER_REPEAT = "CUSTOMER_REPEAT"
    CUSTOMER_ANGER = "CUSTOMER_ANGER"
    CUSTOMER_HUMAN_REQUEST = "CUSTOMER_HUMAN_REQUEST"
    CUSTOMER_CONSENT_YES = "CUSTOMER_CONSENT_YES"
    CUSTOMER_CONSENT_NO = "CUSTOMER_CONSENT_NO"
    CUSTOMER_PROVIDE_INFO = "CUSTOMER_PROVIDE_INFO"
    CUSTOMER_CONFIRM_YES = "CUSTOMER_CONFIRM_YES"
    CUSTOMER_CONFIRM_NO = "CUSTOMER_CONFIRM_NO"
    CUSTOMER_PAYMENT = "CUSTOMER_PAYMENT"
    CUSTOMER_ADVICE = "CUSTOMER_ADVICE"
    CUSTOMER_OFF_SCRIPT = "CUSTOMER_OFF_SCRIPT"
    UNKNOWN = "UNKNOWN"


class EscalationSignal(str, Enum):
    ANGER = "ANGER"
    CONFUSION = "CONFUSION"
    OFF_SCRIPT = "OFF_SCRIPT"
    SENSITIVE = "SENSITIVE"
    HUMAN_REQUEST = "HUMAN_REQUEST"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"


class Mood(str, Enum):
    CALM = "Calm"
    NEUTRAL = "Neutral"
    FRUSTRATED = "Frustrated"
    ESCALATION = "Escalation"


class VoiceMode(str, Enum):
    BROWSER = "BROWSER"
    SIMULATED = "SIMULATED"
    VICIDIAL = "VICIDIAL"
    TWILIO = "TWILIO"


class HandoffStatus(str, Enum):
    WAITING = "WAITING"
    CLAIMED = "CLAIMED"
    RESOLVED = "RESOLVED"
